%RESEARCH_INSTALLATION_TEST    Test if toolboxes are installed.
%                              This is for the research licence 1560.

required_toolboxes = [
    "MATLAB", ...
    "Simulink", ...
    "Bioinformatics Toolbox", ...
    "Control System Toolbox", ...
    "Deep Learning Toolbox", ...
    "Embedded Coder", ...
    "Financial Toolbox", ...
    "Fuzzy Logic Toolbox", ...
    "Global Optimization Toolbox", ...
    "Image Processing Toolbox", ...
    "MATLAB Coder", ...
    "MATLAB Compiler", ...
    "Optimization Toolbox", ...
    "Parallel Computing Toolbox", ...
    "Partial Differential Equation Toolbox", ...
    "Robust Control Toolbox", ...
    "Signal Processing Toolbox", ...
    "Simulink 3D Animation", ...
    "Simulink Coder", ...
    "Simulink Control Design", ...
    "Statistics and Machine Learning Toolbox", ...
    "Symbolic Math Toolbox", ...
    "System Identification Toolbox", ...
    "Wavelet Toolbox"];

if computer('arch') == "win64"
    % OPC and NAG toolboxes only installed for Windows.
    required_toolboxes = [required_toolboxes, "NAG Toolbox", "OPC Toolbox"];
end

%% Any missing toolboxes
missing_toolboxes = are_toolboxes_installed(required_toolboxes);
assert(isempty(missing_toolboxes), "Installation is missing toolboxes!")

%% Any extra toolboxes
extra_toolboxes = detect_extra_toolboxes(required_toolboxes);
assert(isempty(extra_toolboxes), "Installation has extra toolboxes!")
