%TAH_INSTALLATION_TEST    Test if toolboxes are installed.
%                         This is for the TAH licence 40901401.

required_toolboxes = [
    "MATLAB", ...
    "Simulink", ...
    "5G Toolbox", ...
    "AUTOSAR Blockset", ...
    "Aerospace Blockset", ...
    "Aerospace Toolbox", ...
    "Antenna Toolbox", ...
    "Audio Toolbox", ...
    "Automated Driving Toolbox", ...
    "Bioinformatics Toolbox", ...
    "Communications Toolbox", ...
    "Computer Vision Toolbox", ...
    "Control System Toolbox", ...
    "Curve Fitting Toolbox", ...
    "DDS Blockset", ...
    "DSP System Toolbox", ...
    "Data Acquisition Toolbox", ...
    "Database Toolbox", ...
    "Datafeed Toolbox", ...
    "Deep Learning HDL Toolbox", ...
    "Deep Learning Toolbox", ...
    "Econometrics Toolbox", ...
    "Embedded Coder", ...
    "Filter Design HDL Coder", ...
    "Financial Instruments Toolbox", ...
    "Financial Toolbox", ...
    "Fixed-Point Designer", ...
    "Fuzzy Logic Toolbox", ...
    "GPU Coder", ...
    "Global Optimization Toolbox", ...
    "HDL Coder", ...
    "HDL Verifier", ...
    "Image Acquisition Toolbox", ...
    "Image Processing Toolbox", ...
    "Instrument Control Toolbox", ...
    "LTE Toolbox", ...
    "Lidar Toolbox", ...
    "MATLAB Coder", ...
    "MATLAB Compiler SDK", ...
    "MATLAB Compiler", ...
    "MATLAB Report Generator", ...
    "Mapping Toolbox", ...
    "Mixed-Signal Blockset", ...
    "Model Predictive Control Toolbox", ...
    "Model-Based Calibration Toolbox", ...
    "Motor Control Blockset", ...
    "Navigation Toolbox", ...
    "OPC Toolbox", ...
    "Optimization Toolbox", ...
    "Parallel Computing Toolbox", ...
    "Partial Differential Equation Toolbox", ...
    "Phased Array System Toolbox", ...
    "Powertrain Blockset", ...
    "Predictive Maintenance Toolbox", ...
    "RF Blockset", ...
    "RF Toolbox", ...
    "ROS Toolbox", ...
    "Radar Toolbox", ...
    "Reinforcement Learning Toolbox", ...
    "Risk Management Toolbox", ...
    "Robotics System Toolbox", ...
    "Robust Control Toolbox", ...
    "Satellite Communications Toolbox", ...
    "Sensor Fusion and Tracking Toolbox", ...
    "SerDes Toolbox", ...
    "Signal Processing Toolbox", ...
    "SimBiology", ...
    "SimEvents", ...
    "Simscape Driveline", ...
    "Simscape Electrical", ...
    "Simscape Fluids", ...
    "Simscape Multibody", ...
    "Simscape", ...
    "Simulink 3D Animation", ...
    "Simulink Check", ...
    "Simulink Code Inspector", ...
    "Simulink Coder", ...
    "Simulink Compiler", ...
    "Simulink Control Design", ...
    "Simulink Coverage", ...
    "Simulink Design Optimization", ...
    "Simulink Design Verifier", ...
    "Simulink Desktop Real-Time", ...
    "Simulink PLC Coder", ...
    "Simulink Real-Time", ...
    "Simulink Report Generator", ...
    "Simulink Requirements", ...
    "Simulink Test", ...
    "SoC Blockset", ...
    "Spreadsheet Link", ...
    "Stateflow", ...
    "Statistics and Machine Learning Toolbox", ...
    "Symbolic Math Toolbox", ...
    "System Composer", ...
    "System Identification Toolbox", ...
    "Text Analytics Toolbox", ...
    "UAV Toolbox", ...
    "Vehicle Dynamics Blockset", ...
    "Vehicle Network Toolbox", ...
    "Vision HDL Toolbox", ...
    "WLAN Toolbox", ...
    "Wavelet Toolbox", ...
    "Wireless HDL Toolbox"];


%% Any missing toolboxes
missing_toolboxes = are_toolboxes_installed(required_toolboxes);
assert(isempty(missing_toolboxes), "Installation is missing toolboxes!")

%% Any extra toolboxes
extra_toolboxes = detect_extra_toolboxes(required_toolboxes);
assert(isempty(extra_toolboxes), "Installation has extra toolboxes!")
