%ALL_LICENCE_TEST Check TAH licence is in use, and that all toolbox
%                 licences can be checked out
% To test a licence, you have to use the feature name of the product
% as it appears in the licence file, rather than the actual name of the
% toolbox.

feature_names = [...
    "MATLAB", ...
    "SIMULINK", ...
    "MATLAB_5G_Toolbox", ...
    "AUTOSAR_Blockset", ...
    "Aerospace_Blockset", ...
    "Aerospace_Toolbox", ...
    "Antenna_Toolbox", ...
    "Audio_System_Toolbox", ...
    "Automated_Driving_Toolbox", ...
    "Bioinformatics_Toolbox", ...
    "Communication_Toolbox", ...
    "Video_and_Image_Blockset", ...
    "Control_Toolbox", ...
    "Curve_Fitting_Toolbox", ...
    "DDS_Blockset", ...
    "Signal_Blocks", ...
    "Data_Acq_Toolbox", ...
    "Database_Toolbox", ...
    "Datafeed_Toolbox", ...
    "Deep_Learning_HDL_Toolbox", ...
    "Neural_Network_Toolbox", ...
    "Econometrics_Toolbox", ...
    "RTW_Embedded_Coder", ...
    "Filter_Design_HDL_Coder", ...
    "Fin_Instruments_Toolbox", ...
    "Financial_Toolbox", ...
    "Fixed_Point_Toolbox", ...
    "Fuzzy_Toolbox", ...
    "GPU_Coder", ...
    "GADS_Toolbox", ...
    "Simulink_HDL_Coder", ...
    "EDA_Simulator_Link", ...
    "Image_Acquisition_Toolbox", ...
    "Image_Toolbox", ...
    "Instr_Control_Toolbox", ...
    "LTE_Toolbox", ...
    "Lidar_Toolbox", ...
    "MATLAB_Coder", ...
    "MATLAB_Builder_for_Java", ...
    "Compiler", ...
    "MATLAB_Report_Gen", ...
    "MAP_Toolbox", ...
    "Mixed_Signal_Blockset", ...
    "MPC_Toolbox", ...
    "MBC_Toolbox", ...
    "Motor_Control_Blockset", ...
    "Navigation_Toolbox", ...
    "OPC_Toolbox", ...
    "Optimization_Toolbox", ...
    "Distrib_Computing_Toolbox", ...
    "PDE_Toolbox", ...
    "Phased_Array_System_Toolbox", ...
    "Powertrain_Blockset", ...
    "Pred_Maintenance_Toolbox", ...
    "RF_Blockset", ...
    "RF_Toolbox", ...
    "ROS_Toolbox", ...
    "Radar_Toolbox", ...
    "Reinforcement_Learn_Toolbox", ...
    "Risk_Management_Toolbox", ...
    "Robotics_System_Toolbox", ...
    "Robust_Toolbox", ...
    "Satellite_Comm_Toolbox", ...
    "Sensor_Fusion_and_Tracking", ...
    "SerDes_Toolbox", ...
    "Signal_Toolbox", ...
    "SimBiology", ...
    "SimEvents", ...
    "SimDriveline", ...
    "Power_System_Blocks", ...
    "SimHydraulics", ...
    "SimMechanics", ...
    "Simscape", ...
    "Virtual_Reality_Toolbox", ...
    "SL_Verification_Validation", ...
    "Simulink_Code_Inspector", ...
    "Real-Time_Workshop", ...
    "Simulink_Compiler", ...
    "Simulink_Control_Design", ...
    "Simulink_Coverage", ...
    "Simulink_Design_Optim", ...
    "Simulink_Design_Verifier", ...
    "Real-Time_Win_Target", ...
    "Simulink_PLC_Coder", ...
    "XPC_Target", ...
    "SIMULINK_Report_Gen", ...
    "Simulink_Requirements", ...
    "Simulink_Test", ...
    "SoC_Blockset", ...
    "Excel_Link", ...
    "Stateflow", ...
    "Statistics_Toolbox", ...
    "Symbolic_Toolbox", ...
    "System_Composer", ...
    "Identification_Toolbox", ...
    "Text_Analytics_Toolbox", ...
    "UAV_Toolbox", ...
    "Vehicle_Dynamics_Blockset", ...
    "Vehicle_Network_Toolbox", ...
    "Vision_HDL_Toolbox", ...
    "WLAN_System_Toolbox", ...
    "Wavelet_Toolbox", ...
    "LTE_HDL_Toolbox"];

%% Is correct licence in use
TAH_licence = "40901401";
error_message = sprintf("Incorrect licence number in use! Should be using %s instead of %s", TAH_licence, license);
assert(license == TAH_licence, error_message)
fprintf('Correct licence number in use: %s\n', license)

%% Do licences exist
licence_exists = do_licences_exist(feature_names);
assert(all(licence_exists), "Licence doesn't exist for all toolboxes!")

%% Can licences be checked out
check_out_success = check_out_licence(feature_names);
assert(all(check_out_success), 'Unable to check out a licence for all products!')
