%TEACHING_LICENCE_TEST   Test if toolbox licences are available.
%                        This is for the teaching licence 38995.

% To test a licence, you have to use the feature name of the product
% as it appears in the licence file, rather than the actual name of the
% toolbox.

feature_name = ["MATLAB", ...
    "SIMULINK", ...
    "Aerospace_Blockset", ...
    "Aerospace_Toolbox", ...
    "Control_Toolbox", ...
    "Image_Toolbox", ...
    "Optimization_Toolbox", ...
    "Robotics_System_Toolbox", ...
    "Robust_Toolbox", ...
    "Signal_Toolbox", ...
    "Simscape", ...
    "SimHydraulics", ...
    "SimMechanics", ...
    "Power_System_Blocks", ...
    "Video_and_Image_Blockset", ...
    "Virtual_Reality_Toolbox", ...
    "Symbolic_Toolbox", ...
    "Identification_Toolbox"];

%% Is correct licence in use
teaching_licence = "38995";
assert(license == teaching_licence, "Incorrect licence number in use! Should be using %s instead of %s", teaching_licence, license)
fprintf('Correct licence number in use: %s\n\n', license)

%% Do licences exist
licence_exists = do_licences_exist(feature_name);
assert(all(licence_exists), "Licence doesn't exist for all toolboxes!")

%% Can licences be checked out
check_out_success = check_out_licence(feature_name);
assert(all(check_out_success), 'Unable to check out a licence for all products!')
