%TEACHING_LICENCE_TEST   Test if toolbox licences are available.
%                        This is for the teaching licence 38995.

% To test a licence, you have to use the feature name of the product
% as it appears in the licence file, rather than the actual name of the
% toolbox.

feature_name = ["MATLAB", ...
    "SIMULINK", ...
    "Aerospace_Blockset", ...
    "Aerospace_Toolbox", ...
    "Control_Toolbox", ...
    "Robust_Toolbox", ...
    "Simscape", ...
    "SimHydraulics", ...
    "SimMechanics", ...
    "Power_System_Blocks", ...
    "Virtual_Reality_Toolbox", ...
    "Symbolic_Toolbox", ...
    "Identification_Toolbox"];

%% Is correct licence in use
assert(license == "38995", "Incorrect licence number in use!")

%% Do licences exist
licence_exists = do_licences_exist(feature_name);
assert(all(licence_exists), "Licence doesn't exist for all toolboxes!")

%% Can licences be checked out
check_out_success = check_out_licence(feature_name);
assert(all(check_out_success), 'Unable to check out a licence for all products!')